name: Release
on:
  push:
    branches:
      - release/uat
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  release-tag:
    name: Create
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.tag.outputs.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - id: tag
        name: Tag semantic release
        uses: pixelfusion/actions/tag@master
