name: Release
on:
  push:
    branches:
      - release/uat
      - main
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  AWS_ACCESS_KEY_ID: ""
  AWS_SECRET_ACCESS_KEY: ""
  AWS_REGION: ap-southeast-2
jobs:
  setup-env:
    name: Setup environment vars
    outputs:
      version: ${{ steps.tag.outputs.version }}
      aws_access_key_id_name: ${{ steps.aws_creds.outputs.aws_access_key_id_name }}
      aws_secret_access_key_name: ${{ steps.aws_creds.outputs.aws_secret_access_key_name }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Detect Aws creds key names
        id: aws_creds
        run: |
          branch=$(echo "${{ github.ref }}" | sed 's/refs\/heads\///')
          if [[ $branch == 'main' ]]; then
            prefix='PROD'
          elif [[ $branch == 'release/uat' ]]; then
            prefix='UAT'
          else
            echo "Wrong github branch used"
            exit 1
          fi
          
          echo "aws_access_key_id_name=$prefix_AWS_ACCESS_KEY_ID" >> $GITHUB_OUTPUT
          echo "aws_secret_access_key_name=$prefix_AWS_SECRET_ACCESS_KEY" >> $GITHUB_OUTPUT
          echo "Github ref: ${{ github.ref }}"
          echo "Pushed branch: $branch"
      - name: Tag semantic release
        id: tag
        uses: pixelfusion/actions/tag@master
      - name: Detect changes
        id: changes
        run: |
          echo "Running CI/CD under ${{ env.ENVIRONMENT }}"
          git fetch origin ${{ env.RELEASE_BRANCH }}:refs/remotes/origin/${{ env.RELEASE_BRANCH }}
          ADMIN_DIFF=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} -- ./admin)
          if [ -n "$ADMIN_DIFF" ]; then
            echo "admin=true" >> $GITHUB_OUTPUT
          else
            echo "admin=false" >> $GITHUB_OUTPUT
          fi
          INFRA_DIFF=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} -- ./infra)
          if [ -n "$INFRA_DIFF" ]; then
            echo "infra=true" >> $GITHUB_OUTPUT
          else
            echo "infra=false" >> $GITHUB_OUTPUT
          fi
      - name: test here
        run: |
          echo "admin=${{ steps.changes.outputs.admin }}"
          echo "infra=${{ steps.changes.outputs.infra }}"
      - name: Build Infra
        if: ${{ steps.changes.outputs.infra == 'true' }}
        run: |
          echo "build infra"
      - name: Register nova authentication
        if: ${{  steps.changes.outputs.infra == 'true' ||  steps.changes.outputs.admin == 'true'  }}
        run: |
          echo 'register nova admin'
      - name: Build Admin
        if: ${{  steps.changes.outputs.infra == 'true' ||  steps.changes.outputs.admin == 'true'  }}
        run: |
          echo "build admin"
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: setup-env
    steps:
      - name: Test Echo
        run: |
          echo "Checking deploy envs"
          echo ${{needs.setup-env.outputs.aws_access_key_id_name}}
          echo ${{needs.setup-env.outputs.aws_secret_access_key_name}}


