name: Release
on:
  push:
    branches:
      - release/uat
      - main
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  setup-env:
    name: Setup environment vars
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set environment based on branch
        run: |
          branch=$(echo "${{ github.ref }}" | sed 's/refs\/heads\///')
          if [[ $branch == 'main' ]]; then
            echo "ENVIRONMENT=prod" >> $GITHUB_ENV
            echo "AWS_ACCESS_KEY_ID=${{ secrets.PROD_AWS_ACCESS_KEY_ID }}" >> $GITHUB_ENV
            echo "AWS_SECRET_ACCESS_KEY=${{ secrets.PROD_AWS_SECRET_ACCESS_KEY }}" >> $GITHUB_ENV
          elif [[ $branch == 'release/uat' ]]; then
            echo "ENVIRONMENT=uat" >> $GITHUB_ENV
            echo "AWS_ACCESS_KEY_ID=${{ secrets.UAT_AWS_ACCESS_KEY_ID }}" >> $GITHUB_ENV
            echo "AWS_SECRET_ACCESS_KEY=${{ secrets.UAT_AWS_SECRET_ACCESS_KEY }}" >> $GITHUB_ENV
          else
            echo "wrong github branch used"
            exit 1
          fi
          echo "GITHUB_BRANCH=$branch" >> $GITHUB_ENV
          echo "Github ref: ${{ github.ref }}"
          echo "Pushed branch: $branch"
      - name: Detect changes
        id: detect_changes
        run: |
          echo "Running CI/CD under ${{ env.ENVIRONMENT }}"
          git fetch origin ${{ env.GITHUB_BRANCH }}:refs/remotes/origin/${{ env.GITHUB_BRANCH }}
          ADMIN_DIFF=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} -- ./admin)
          if [ -n "$ADMIN_DIFF" ]; then
            ADMIN_HAS_CHANGES=true
          else
            ADMIN_HAS_CHANGES=false
          fi
          echo "ADMIN_DIFF=$ADMIN_DIFF" >> $GITHUB_ENV
          INFRA_DIFF=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} -- ./infra)
          if [ -n "$INFRA_DIFF" ]; then
            INFRA_HAS_CHANGES=true
          else
            INFRA_HAS_CHANGES=false
          fi
          echo "INFRA_HAS_CHANGES=$INFRA_HAS_CHANGES" >> $GITHUB_ENV
      - name: Check envs
        run: |
          echo "checking"
  release-build:
    name: Semantic Release and Build
    needs: setup-env
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.tag.outputs.version }}
    steps:
      - id: tag
        name: Tag semantic release
        uses: pixelfusion/actions/tag@master
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: release-build
    steps:
      - name: Test Echo
        run: |
          echo "Checking deploy envs"


