name: Release
on:
  push:
    branches:
      - main
      - release/uat
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  release:
    name: Create
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - id: tag
        name: Tag semantic release
        uses: pixelfusion/actions/tag@master
