name: Release
on:
  push:
    branches:
      - release/uat
      - main
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  release-tag:
    name: Release and Tag
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.tag.outputs.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set environment based on branch
        run: |
          if [[ ${{ github.ref }} == 'refs/heads/main' ]]; then
            echo "ENVIRONMENT=prod" >> $GITHUB_ENV
          elif [[ ${{ github.ref }} == 'refs/heads/release/uat' ]]; then
            echo "ENVIRONMENT=uat" >> $GITHUB_ENV
          else
            exit 1
          fi
      - id: tag
        name: Tag semantic release
        uses: pixelfusion/actions/tag@master
      - name: Check output
        run: |
          branch=$(echo "${{ github.ref }}" | sed 's/refs\/heads\///')
          echo "Running CI/CD under ${{ env.ENVIRONMENT }}"
          echo "Github ref: ${{ github.ref }}"
          echo "Pushed branch: $branch"
          echo "Version: ${{ steps.tag.outputs.version }}"
      - name: Detect changes in admin folder
        id: diff_admin
        run: |
          git fetch origin main:refs/remotes/origin/main
          DIFF=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} -- ./admin)
          echo "DIFF=$DIFF" >> $GITHUB_ENV
          echo $DIFF
      - name: Detect changes in infra folder
        id: diff_infra
        run: |
          git fetch origin main:refs/remotes/origin/main
          DIFF=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} -- ./infra)
          echo "DIFF=$DIFF" >> $GITHUB_ENV
          echo $DIFF
      

