name: Release
on:
  push:
    branches:
      - release/uat
      - main
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  release-tag:
    name: Release and Tag
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.tag.outputs.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set environment based on branch
        run: |
          branch=$(echo "${{ github.ref }}" | sed 's/refs\/heads\///')
          if [[ $branch == 'main' ]]; then
            echo "ENVIRONMENT=prod" >> $GITHUB_ENV
            echo "AWS_ACCESS_KEY_ID=${{ env.PROD_AWS_ACCESS_KEY_ID }}" >> $GITHUB_ENV
            echo "AWS_SECRET_ACCESS_KEY=${{ env.PROD_AWS_SECRET_ACCESS_KEY }}" >> $GITHUB_ENV
          elif [[ $branch == 'release/uat' ]]; then
            echo "ENVIRONMENT=uat" >> $GITHUB_ENV
            echo "AWS_ACCESS_KEY_ID=${{ env.UAT_AWS_ACCESS_KEY_ID }}" >> $GITHUB_ENV
            echo "AWS_SECRET_ACCESS_KEY=${{ env.UAT_AWS_SECRET_ACCESS_KEY }}" >> $GITHUB_ENV
          else
            echo "wrong github branch used"
            exit 1
          fi
          echo "GITHUB_BRANCH=$branch" >> $GITHUB_ENV
          echo "Github ref: ${{ github.ref }}"
          echo "Pushed branch: $branch"
          echo "Version: ${{ steps.tag.outputs.version }}"
      - id: tag
        name: Tag semantic release
        uses: pixelfusion/actions/tag@master
      - name: Detect changes
        id: detect_changes
        run: |
          echo "Running CI/CD under ${{ env.ENVIRONMENT }}"
          echo "RELEASE_VERSION=${{ steps.tag.outputs.version }}" >> $GITHUB_ENV
          echo "Version: ${{ steps.tag.outputs.version }}"
          git fetch origin ${{ env.GITHUB_BRANCH }}:refs/remotes/origin/${{ env.GITHUB_BRANCH }}
          ADMIN_DIFF=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} -- ./admin)
          echo "ADMIN_DIFF=$ADMIN_DIFF" >> $GITHUB_ENV
          INFRA_DIFF=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} -- ./infra)
          echo "INFRA_DIFF=$INFRA_DIFF" >> $GITHUB_ENV
      

