name: Release
on:
  push:
    branches:
      - release/uat
      - main
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  release-tag:
    name: Create
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.tag.outputs.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - id: tag
        name: Tag semantic release
        uses: pixelfusion/actions/tag@master
      - name: Check output
        run: |
          branch=$(echo "${{ github.ref }}" | sed 's/refs\/heads\///')
          echo "Github ref: ${{ github.ref }}"
          echo "Pushed branch: $branch"
          echo "Version: ${{ steps.tag.outputs.version }}"
      - name: Detect changes in admin folder
        id: diff
        run: |
          git fetch origin main:refs/remotes/origin/main
          DIFF=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} -- ./admin)
          echo "DIFF=$DIFF" >> $GITHUB_ENV
          echo $DIFF

